### ISSUE TITLE
Vigiles does not seem to work with meta-freescale?

### ISSUE THREAD

**Issue by ssfivy** [TimesysGit/meta-timesys#2] opened 2020-09-16 09:58 UTC
Hello,

Vigiles does not seem to work when trying to build a hardware from meta-freescale layer:

```
Parsing recipes: 100% |#################################################################################| Time: 0:00:12
Parsing of 907 .bb files complete (0 cached, 907 parsed). 1467 targets, 164 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'linux-fslc-imx'
linux-fslc-imx was skipped: incompatible with machine imx7dsabresd (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'linux-fslc-imx']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
```

I found that getting rid of `INHERIT += "vigiles"` in local.conf seems to make builds working again.

My entire test script is below. If the second to last line is uncommented the build will break. Comment it again and build will proceed normally.

```
#!/bin/bash

set -xe

THIS_SCRIPT_DIR=$(dirname "$(realpath -s $0)")

# Get layers
if [ -d poky ]; then
    pushd poky
    git pull
    popd
else
    git clone -b dunfell --depth 1 git://git.yoctoproject.org/poky.git
fi

if [ -d meta-freescale ]; then
    pushd meta-freescale
    git pull
    popd
else
    git clone -b dunfell --depth 1 https://github.com/Freescale/meta-freescale.git
fi

if [ -d meta-timesys ]; then
    pushd meta-timesys
    git pull
    popd
else
    git clone -b dunfell --depth 1 https://github.com/TimeSysGit/meta-timesys.git
fi

# Clean previous local.conf modifications
rm -f "$THIS_SCRIPT_DIR/build/conf/local.conf"

# Source bitbake setup script (should regenerate local.conf)
source "poky/oe-init-build-env"

# Add extra layers
bitbake-layers add-layer "$THIS_SCRIPT_DIR/meta-freescale"
bitbake-layers add-layer "$THIS_SCRIPT_DIR/meta-timesys"

# Modify local.conf
echo '' >> "$THIS_SCRIPT_DIR/build/conf/local.conf"
echo 'MACHINE = "imx7dsabresd"' >> "$THIS_SCRIPT_DIR/build/conf/local.conf"

# Uncommenting this will break build
#echo 'INHERIT += "vigiles" ' >> "$THIS_SCRIPT_DIR/build/conf/local.conf"

bitbake core-image-minimal

```

**Comment by mgpb** [comment] 2020-09-16 20:55
Thanks for the report, and for the script that easily reproduces it!

We are working on the fix, but as a workaround for now, it looks like explicitly setting the kernel provider will get the build going. I added it to your script this way:
```
echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-fslc"' >> "$THIS_SCRIPT_DIR/build/conf/local.conf"
```

**Comment by ssfivy** [comment] 2020-09-17 02:08
No worries, I did find that as a workaround to get things to compile (alongside overwriting COMPATIBLE_MACHINE for the kernel recipe with bbappend). 

I am a bit wary of workarounds though since there might be other configurations that didnt get applied but didnt break the build (and meta-freescale's imx-base.inc file looks really complex, so I couldn't figure it out myself).

**Comment by iancampbell** [comment] 2020-09-30 23:05
Fixed by: https://github.com/TimesysGit/meta-timesys/commit/a2aca9e566ed7303f1ce2b0cd846a1ea4643e289

**Closed by iancampbell** 2020-09-30 23:05 UTC
Labels: bug
